"""add_all_prd_models

Revision ID: c4cd6f5a4f64
Revises: 1a31ce608336
Create Date: 2025-12-14 22:59:20.371298

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4cd6f5a4f64'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentcontextcache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('context_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentcontextcache_agent_id'), 'agentcontextcache', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agentcontextcache_context_key'), 'agentcontextcache', ['context_key'], unique=False)
    op.create_table('agentframeworkconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework')
    )
    op.create_table('agenttask',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_framework', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('browsersession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('browser_tool', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('proxy_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browsersession_session_id'), 'browsersession', ['session_id'], unique=True)
    op.create_table('changedetection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('diff_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('previous_content', sqlmodel.sql.sqltypes.AutoString(length=1000000), nullable=True),
    sa.Column('current_content', sqlmodel.sql.sqltypes.AutoString(length=1000000), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changedetection_diff_hash'), 'changedetection', ['diff_hash'], unique=False)
    op.create_index(op.f('ix_changedetection_url'), 'changedetection', ['url'], unique=False)
    op.create_table('codeexecution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('runtime', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100000), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connector',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('latest_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_slug'), 'connector', ['slug'], unique=True)
    op.create_table('contentchecksum',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentchecksum_content_hash'), 'contentchecksum', ['content_hash'], unique=False)
    op.create_index(op.f('ix_contentchecksum_url'), 'contentchecksum', ['url'], unique=False)
    op.create_table('domainprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('max_requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('requires_login', sa.Boolean(), nullable=False),
    sa.Column('captcha_likelihood', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('scroll_needed', sa.Boolean(), nullable=False),
    sa.Column('idle_before_click', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domainprofile_domain'), 'domainprofile', ['domain'], unique=True)
    op.create_table('eventlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventlog_created_at'), 'eventlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_eventlog_event_type'), 'eventlog', ['event_type'], unique=False)
    op.create_table('modelcostlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('usd_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelcostlog_agent_id'), 'modelcostlog', ['agent_id'], unique=False)
    op.create_index(op.f('ix_modelcostlog_created_at'), 'modelcostlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_modelcostlog_model'), 'modelcostlog', ['model'], unique=False)
    op.create_table('ocrjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osintstream',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxylog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('domain_scraped', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('block_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxylog_domain_scraped'), 'proxylog', ['domain_scraped'], unique=False)
    op.create_index(op.f('ix_proxylog_ip_id'), 'proxylog', ['ip_id'], unique=False)
    op.create_table('scrapejob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('proxy_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolusagelog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tool_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolusagelog_created_at'), 'toolusagelog', ['created_at'], unique=False)
    op.create_index(op.f('ix_toolusagelog_tool_id'), 'toolusagelog', ['tool_id'], unique=False)
    op.create_index(op.f('ix_toolusagelog_tool_type'), 'toolusagelog', ['tool_type'], unique=False)
    op.create_table('agenttasklog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agenttask.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenttasklog_task_id'), 'agenttasklog', ['task_id'], unique=False)
    op.create_table('browseraction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['browsersession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codesandbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('runtime', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codetoolregistry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100000), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('runtime', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codetoolregistry_tool_id'), 'codetoolregistry', ['tool_id'], unique=True)
    op.create_table('connectorversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wheel_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectorversion_connector_id'), 'connectorversion', ['connector_id'], unique=False)
    op.create_table('ocrdocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ocrjob.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocrresult',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(length=100000), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ocrjob.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osintalert',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['osintstream.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osintsignal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['osintstream.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ragindex',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vector_db_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraperesult',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=1000000), nullable=False),
    sa.Column('html', sqlmodel.sql.sqltypes.AutoString(length=10000000), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scrapejob.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('graph_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ragdocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=100000), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['ragindex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ragfinetunejob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['ragindex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ragquery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['ragindex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ragquery_index_id'), 'ragquery', ['index_id'], unique=False)
    op.create_index(op.f('ix_ragquery_created_at'), 'ragquery', ['created_at'], unique=False)
    op.create_table('webhooksubscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connector_version_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_secret', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_version_id'], ['connectorversion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflowexecution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_node_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('execution_state', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowexecution_execution_id'), 'workflowexecution', ['execution_id'], unique=True)
    op.create_index(op.f('ix_workflowexecution_workflow_id'), 'workflowexecution', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflowexecution_status'), 'workflowexecution', ['status'], unique=False)
    op.create_index(op.f('ix_workflowexecution_started_at'), 'workflowexecution', ['started_at'], unique=False)
    op.create_table('workflownode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflowschedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executionlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflowexecution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executionlog_execution_id'), 'executionlog', ['execution_id'], unique=False)
    op.create_index(op.f('ix_executionlog_timestamp'), 'executionlog', ['timestamp'], unique=False)
    op.create_table('ragfinetunedataset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ragfinetunejob.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ragswitchlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.Column('routing_decision', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('routing_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['ragquery.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflowsignal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('signal_data', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflowexecution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'])
    op.drop_table('workflowsignal')
    op.drop_table('ragswitchlog')
    op.drop_table('ragfinetunedataset')
    op.drop_index(op.f('ix_executionlog_timestamp'), table_name='executionlog')
    op.drop_index(op.f('ix_executionlog_execution_id'), table_name='executionlog')
    op.drop_table('executionlog')
    op.drop_table('workflowschedule')
    op.drop_table('workflownode')
    op.drop_index(op.f('ix_workflowexecution_started_at'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_status'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_workflow_id'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_execution_id'), table_name='workflowexecution')
    op.drop_table('workflowexecution')
    op.drop_table('webhooksubscription')
    op.drop_index(op.f('ix_ragquery_created_at'), table_name='ragquery')
    op.drop_index(op.f('ix_ragquery_index_id'), table_name='ragquery')
    op.drop_table('ragquery')
    op.drop_table('ragfinetunejob')
    op.drop_table('ragdocument')
    op.drop_table('workflow')
    op.drop_table('scraperesult')
    op.drop_table('ragindex')
    op.drop_table('osintsignal')
    op.drop_table('osintalert')
    op.drop_table('ocrresult')
    op.drop_table('ocrdocument')
    op.drop_index(op.f('ix_connectorversion_connector_id'), table_name='connectorversion')
    op.drop_table('connectorversion')
    op.drop_index(op.f('ix_codetoolregistry_tool_id'), table_name='codetoolregistry')
    op.drop_table('codetoolregistry')
    op.drop_table('codesandbox')
    op.drop_table('browseraction')
    op.drop_index(op.f('ix_agenttasklog_task_id'), table_name='agenttasklog')
    op.drop_table('agenttasklog')
    op.drop_index(op.f('ix_toolusagelog_tool_type'), table_name='toolusagelog')
    op.drop_index(op.f('ix_toolusagelog_tool_id'), table_name='toolusagelog')
    op.drop_index(op.f('ix_toolusagelog_created_at'), table_name='toolusagelog')
    op.drop_table('toolusagelog')
    op.drop_table('scrapejob')
    op.drop_index(op.f('ix_proxylog_ip_id'), table_name='proxylog')
    op.drop_index(op.f('ix_proxylog_domain_scraped'), table_name='proxylog')
    op.drop_table('proxylog')
    op.drop_table('osintstream')
    op.drop_table('ocrjob')
    op.drop_index(op.f('ix_modelcostlog_model'), table_name='modelcostlog')
    op.drop_index(op.f('ix_modelcostlog_created_at'), table_name='modelcostlog')
    op.drop_index(op.f('ix_modelcostlog_agent_id'), table_name='modelcostlog')
    op.drop_table('modelcostlog')
    op.drop_index(op.f('ix_eventlog_event_type'), table_name='eventlog')
    op.drop_index(op.f('ix_eventlog_created_at'), table_name='eventlog')
    op.drop_table('eventlog')
    op.drop_index(op.f('ix_domainprofile_domain'), table_name='domainprofile')
    op.drop_table('domainprofile')
    op.drop_index(op.f('ix_contentchecksum_url'), table_name='contentchecksum')
    op.drop_index(op.f('ix_contentchecksum_content_hash'), table_name='contentchecksum')
    op.drop_table('contentchecksum')
    op.drop_index(op.f('ix_connector_slug'), table_name='connector')
    op.drop_table('connector')
    op.drop_table('codeexecution')
    op.drop_index(op.f('ix_changedetection_url'), table_name='changedetection')
    op.drop_index(op.f('ix_changedetection_diff_hash'), table_name='changedetection')
    op.drop_table('changedetection')
    op.drop_index(op.f('ix_browsersession_session_id'), table_name='browsersession')
    op.drop_table('browsersession')
    op.drop_table('agenttask')
    op.drop_table('agentframeworkconfig')
    op.drop_index(op.f('ix_agentcontextcache_context_key'), table_name='agentcontextcache')
    op.drop_index(op.f('ix_agentcontextcache_agent_id'), table_name='agentcontextcache')
    op.drop_table('agentcontextcache')
    # ### end Alembic commands ###
