/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkflowsRouteImport } from './routes/_layout/workflows'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutScrapingRouteImport } from './routes/_layout/scraping'
import { Route as LayoutRagRouteImport } from './routes/_layout/rag'
import { Route as LayoutOsintRouteImport } from './routes/_layout/osint'
import { Route as LayoutOcrRouteImport } from './routes/_layout/ocr'
import { Route as LayoutConnectorsRouteImport } from './routes/_layout/connectors'
import { Route as LayoutCodeRouteImport } from './routes/_layout/code'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutBrowserRouteImport } from './routes/_layout/browser'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkflowsRoute = LayoutWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScrapingRoute = LayoutScrapingRouteImport.update({
  id: '/scraping',
  path: '/scraping',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRagRoute = LayoutRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOsintRoute = LayoutOsintRouteImport.update({
  id: '/osint',
  path: '/osint',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOcrRoute = LayoutOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectorsRoute = LayoutConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCodeRoute = LayoutCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrowserRoute = LayoutBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/browser': typeof LayoutBrowserRoute
  '/chat': typeof LayoutChatRoute
  '/code': typeof LayoutCodeRoute
  '/connectors': typeof LayoutConnectorsRoute
  '/ocr': typeof LayoutOcrRoute
  '/osint': typeof LayoutOsintRoute
  '/rag': typeof LayoutRagRoute
  '/scraping': typeof LayoutScrapingRoute
  '/settings': typeof LayoutSettingsRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/browser': typeof LayoutBrowserRoute
  '/chat': typeof LayoutChatRoute
  '/code': typeof LayoutCodeRoute
  '/connectors': typeof LayoutConnectorsRoute
  '/ocr': typeof LayoutOcrRoute
  '/osint': typeof LayoutOsintRoute
  '/rag': typeof LayoutRagRoute
  '/scraping': typeof LayoutScrapingRoute
  '/settings': typeof LayoutSettingsRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/browser': typeof LayoutBrowserRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/code': typeof LayoutCodeRoute
  '/_layout/connectors': typeof LayoutConnectorsRoute
  '/_layout/ocr': typeof LayoutOcrRoute
  '/_layout/osint': typeof LayoutOsintRoute
  '/_layout/rag': typeof LayoutRagRoute
  '/_layout/scraping': typeof LayoutScrapingRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/workflows': typeof LayoutWorkflowsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/browser'
    | '/chat'
    | '/code'
    | '/connectors'
    | '/ocr'
    | '/osint'
    | '/rag'
    | '/scraping'
    | '/settings'
    | '/workflows'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/browser'
    | '/chat'
    | '/code'
    | '/connectors'
    | '/ocr'
    | '/osint'
    | '/rag'
    | '/scraping'
    | '/settings'
    | '/workflows'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/agents'
    | '/_layout/browser'
    | '/_layout/chat'
    | '/_layout/code'
    | '/_layout/connectors'
    | '/_layout/ocr'
    | '/_layout/osint'
    | '/_layout/rag'
    | '/_layout/scraping'
    | '/_layout/settings'
    | '/_layout/workflows'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workflows': {
      id: '/_layout/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof LayoutWorkflowsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scraping': {
      id: '/_layout/scraping'
      path: '/scraping'
      fullPath: '/scraping'
      preLoaderRoute: typeof LayoutScrapingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rag': {
      id: '/_layout/rag'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof LayoutRagRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/osint': {
      id: '/_layout/osint'
      path: '/osint'
      fullPath: '/osint'
      preLoaderRoute: typeof LayoutOsintRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ocr': {
      id: '/_layout/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof LayoutOcrRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connectors': {
      id: '/_layout/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof LayoutConnectorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/code': {
      id: '/_layout/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof LayoutCodeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/browser': {
      id: '/_layout/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof LayoutBrowserRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutBrowserRoute: typeof LayoutBrowserRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCodeRoute: typeof LayoutCodeRoute
  LayoutConnectorsRoute: typeof LayoutConnectorsRoute
  LayoutOcrRoute: typeof LayoutOcrRoute
  LayoutOsintRoute: typeof LayoutOsintRoute
  LayoutRagRoute: typeof LayoutRagRoute
  LayoutScrapingRoute: typeof LayoutScrapingRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWorkflowsRoute: typeof LayoutWorkflowsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutBrowserRoute: LayoutBrowserRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutCodeRoute: LayoutCodeRoute,
  LayoutConnectorsRoute: LayoutConnectorsRoute,
  LayoutOcrRoute: LayoutOcrRoute,
  LayoutOsintRoute: LayoutOsintRoute,
  LayoutRagRoute: LayoutRagRoute,
  LayoutScrapingRoute: LayoutScrapingRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWorkflowsRoute: LayoutWorkflowsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
