/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkflowsRouteImport } from './routes/_layout/workflows'
import { Route as LayoutTeamsRouteImport } from './routes/_layout/teams'
import { Route as LayoutStorageRouteImport } from './routes/_layout/storage'
import { Route as LayoutSocialMonitoringRouteImport } from './routes/_layout/social-monitoring'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutScrapingRouteImport } from './routes/_layout/scraping'
import { Route as LayoutRagRouteImport } from './routes/_layout/rag'
import { Route as LayoutOsintRouteImport } from './routes/_layout/osint'
import { Route as LayoutOcrRouteImport } from './routes/_layout/ocr'
import { Route as LayoutConnectorsRouteImport } from './routes/_layout/connectors'
import { Route as LayoutCodeRouteImport } from './routes/_layout/code'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutBrowserRouteImport } from './routes/_layout/browser'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as TeamsInvitationsAcceptRouteImport } from './routes/teams/invitations/accept'
import { Route as LayoutSettingsTeamsRouteImport } from './routes/_layout/settings/teams'
import { Route as LayoutSettingsSecurityRouteImport } from './routes/_layout/settings/security'
import { Route as LayoutSettingsProfileRouteImport } from './routes/_layout/settings/profile'
import { Route as LayoutSettingsPreferencesRouteImport } from './routes/_layout/settings/preferences'
import { Route as LayoutSettingsNotificationsRouteImport } from './routes/_layout/settings/notifications'
import { Route as LayoutSettingsIntegrationsRouteImport } from './routes/_layout/settings/integrations'
import { Route as LayoutSettingsDeveloperRouteImport } from './routes/_layout/settings/developer'
import { Route as LayoutSettingsDataRouteImport } from './routes/_layout/settings/data'
import { Route as LayoutSettingsDangerRouteImport } from './routes/_layout/settings/danger'
import { Route as LayoutSettingsAppearanceRouteImport } from './routes/_layout/settings/appearance'
import { Route as LayoutSettingsApiKeysRouteImport } from './routes/_layout/settings/api-keys'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkflowsRoute = LayoutWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsRoute = LayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStorageRoute = LayoutStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSocialMonitoringRoute = LayoutSocialMonitoringRouteImport.update({
  id: '/social-monitoring',
  path: '/social-monitoring',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScrapingRoute = LayoutScrapingRouteImport.update({
  id: '/scraping',
  path: '/scraping',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRagRoute = LayoutRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOsintRoute = LayoutOsintRouteImport.update({
  id: '/osint',
  path: '/osint',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOcrRoute = LayoutOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectorsRoute = LayoutConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCodeRoute = LayoutCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrowserRoute = LayoutBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const TeamsInvitationsAcceptRoute = TeamsInvitationsAcceptRouteImport.update({
  id: '/teams/invitations/accept',
  path: '/teams/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsTeamsRoute = LayoutSettingsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsSecurityRoute = LayoutSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsProfileRoute = LayoutSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsPreferencesRoute =
  LayoutSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsNotificationsRoute =
  LayoutSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsIntegrationsRoute =
  LayoutSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsDeveloperRoute = LayoutSettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsDataRoute = LayoutSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsDangerRoute = LayoutSettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsAppearanceRoute =
  LayoutSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsApiKeysRoute = LayoutSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => LayoutSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/browser': typeof LayoutBrowserRoute
  '/chat': typeof LayoutChatRoute
  '/code': typeof LayoutCodeRoute
  '/connectors': typeof LayoutConnectorsRoute
  '/ocr': typeof LayoutOcrRoute
  '/osint': typeof LayoutOsintRoute
  '/rag': typeof LayoutRagRoute
  '/scraping': typeof LayoutScrapingRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/social-monitoring': typeof LayoutSocialMonitoringRoute
  '/storage': typeof LayoutStorageRoute
  '/teams': typeof LayoutTeamsRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/': typeof LayoutIndexRoute
  '/settings/api-keys': typeof LayoutSettingsApiKeysRoute
  '/settings/appearance': typeof LayoutSettingsAppearanceRoute
  '/settings/danger': typeof LayoutSettingsDangerRoute
  '/settings/data': typeof LayoutSettingsDataRoute
  '/settings/developer': typeof LayoutSettingsDeveloperRoute
  '/settings/integrations': typeof LayoutSettingsIntegrationsRoute
  '/settings/notifications': typeof LayoutSettingsNotificationsRoute
  '/settings/preferences': typeof LayoutSettingsPreferencesRoute
  '/settings/profile': typeof LayoutSettingsProfileRoute
  '/settings/security': typeof LayoutSettingsSecurityRoute
  '/settings/teams': typeof LayoutSettingsTeamsRoute
  '/teams/invitations/accept': typeof TeamsInvitationsAcceptRoute
  '/settings/': typeof LayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/browser': typeof LayoutBrowserRoute
  '/chat': typeof LayoutChatRoute
  '/code': typeof LayoutCodeRoute
  '/connectors': typeof LayoutConnectorsRoute
  '/ocr': typeof LayoutOcrRoute
  '/osint': typeof LayoutOsintRoute
  '/rag': typeof LayoutRagRoute
  '/scraping': typeof LayoutScrapingRoute
  '/social-monitoring': typeof LayoutSocialMonitoringRoute
  '/storage': typeof LayoutStorageRoute
  '/teams': typeof LayoutTeamsRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/': typeof LayoutIndexRoute
  '/settings/api-keys': typeof LayoutSettingsApiKeysRoute
  '/settings/appearance': typeof LayoutSettingsAppearanceRoute
  '/settings/danger': typeof LayoutSettingsDangerRoute
  '/settings/data': typeof LayoutSettingsDataRoute
  '/settings/developer': typeof LayoutSettingsDeveloperRoute
  '/settings/integrations': typeof LayoutSettingsIntegrationsRoute
  '/settings/notifications': typeof LayoutSettingsNotificationsRoute
  '/settings/preferences': typeof LayoutSettingsPreferencesRoute
  '/settings/profile': typeof LayoutSettingsProfileRoute
  '/settings/security': typeof LayoutSettingsSecurityRoute
  '/settings/teams': typeof LayoutSettingsTeamsRoute
  '/teams/invitations/accept': typeof TeamsInvitationsAcceptRoute
  '/settings': typeof LayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/browser': typeof LayoutBrowserRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/code': typeof LayoutCodeRoute
  '/_layout/connectors': typeof LayoutConnectorsRoute
  '/_layout/ocr': typeof LayoutOcrRoute
  '/_layout/osint': typeof LayoutOsintRoute
  '/_layout/rag': typeof LayoutRagRoute
  '/_layout/scraping': typeof LayoutScrapingRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/social-monitoring': typeof LayoutSocialMonitoringRoute
  '/_layout/storage': typeof LayoutStorageRoute
  '/_layout/teams': typeof LayoutTeamsRoute
  '/_layout/workflows': typeof LayoutWorkflowsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/settings/api-keys': typeof LayoutSettingsApiKeysRoute
  '/_layout/settings/appearance': typeof LayoutSettingsAppearanceRoute
  '/_layout/settings/danger': typeof LayoutSettingsDangerRoute
  '/_layout/settings/data': typeof LayoutSettingsDataRoute
  '/_layout/settings/developer': typeof LayoutSettingsDeveloperRoute
  '/_layout/settings/integrations': typeof LayoutSettingsIntegrationsRoute
  '/_layout/settings/notifications': typeof LayoutSettingsNotificationsRoute
  '/_layout/settings/preferences': typeof LayoutSettingsPreferencesRoute
  '/_layout/settings/profile': typeof LayoutSettingsProfileRoute
  '/_layout/settings/security': typeof LayoutSettingsSecurityRoute
  '/_layout/settings/teams': typeof LayoutSettingsTeamsRoute
  '/teams/invitations/accept': typeof TeamsInvitationsAcceptRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/browser'
    | '/chat'
    | '/code'
    | '/connectors'
    | '/ocr'
    | '/osint'
    | '/rag'
    | '/scraping'
    | '/settings'
    | '/social-monitoring'
    | '/storage'
    | '/teams'
    | '/workflows'
    | '/'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/developer'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/teams'
    | '/teams/invitations/accept'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/browser'
    | '/chat'
    | '/code'
    | '/connectors'
    | '/ocr'
    | '/osint'
    | '/rag'
    | '/scraping'
    | '/social-monitoring'
    | '/storage'
    | '/teams'
    | '/workflows'
    | '/'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/developer'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/teams'
    | '/teams/invitations/accept'
    | '/settings'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/agents'
    | '/_layout/browser'
    | '/_layout/chat'
    | '/_layout/code'
    | '/_layout/connectors'
    | '/_layout/ocr'
    | '/_layout/osint'
    | '/_layout/rag'
    | '/_layout/scraping'
    | '/_layout/settings'
    | '/_layout/social-monitoring'
    | '/_layout/storage'
    | '/_layout/teams'
    | '/_layout/workflows'
    | '/_layout/'
    | '/_layout/settings/api-keys'
    | '/_layout/settings/appearance'
    | '/_layout/settings/danger'
    | '/_layout/settings/data'
    | '/_layout/settings/developer'
    | '/_layout/settings/integrations'
    | '/_layout/settings/notifications'
    | '/_layout/settings/preferences'
    | '/_layout/settings/profile'
    | '/_layout/settings/security'
    | '/_layout/settings/teams'
    | '/teams/invitations/accept'
    | '/_layout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TeamsInvitationsAcceptRoute: typeof TeamsInvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workflows': {
      id: '/_layout/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof LayoutWorkflowsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/storage': {
      id: '/_layout/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof LayoutStorageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/social-monitoring': {
      id: '/_layout/social-monitoring'
      path: '/social-monitoring'
      fullPath: '/social-monitoring'
      preLoaderRoute: typeof LayoutSocialMonitoringRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scraping': {
      id: '/_layout/scraping'
      path: '/scraping'
      fullPath: '/scraping'
      preLoaderRoute: typeof LayoutScrapingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rag': {
      id: '/_layout/rag'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof LayoutRagRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/osint': {
      id: '/_layout/osint'
      path: '/osint'
      fullPath: '/osint'
      preLoaderRoute: typeof LayoutOsintRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ocr': {
      id: '/_layout/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof LayoutOcrRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connectors': {
      id: '/_layout/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof LayoutConnectorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/code': {
      id: '/_layout/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof LayoutCodeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/browser': {
      id: '/_layout/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof LayoutBrowserRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/teams/invitations/accept': {
      id: '/teams/invitations/accept'
      path: '/teams/invitations/accept'
      fullPath: '/teams/invitations/accept'
      preLoaderRoute: typeof TeamsInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings/teams': {
      id: '/_layout/settings/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof LayoutSettingsTeamsRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/security': {
      id: '/_layout/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutSettingsSecurityRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/profile': {
      id: '/_layout/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutSettingsProfileRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/preferences': {
      id: '/_layout/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof LayoutSettingsPreferencesRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/notifications': {
      id: '/_layout/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof LayoutSettingsNotificationsRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/integrations': {
      id: '/_layout/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof LayoutSettingsIntegrationsRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/developer': {
      id: '/_layout/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof LayoutSettingsDeveloperRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/data': {
      id: '/_layout/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof LayoutSettingsDataRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/danger': {
      id: '/_layout/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof LayoutSettingsDangerRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/appearance': {
      id: '/_layout/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof LayoutSettingsAppearanceRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/api-keys': {
      id: '/_layout/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof LayoutSettingsApiKeysRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
  }
}

interface LayoutSettingsRouteChildren {
  LayoutSettingsApiKeysRoute: typeof LayoutSettingsApiKeysRoute
  LayoutSettingsAppearanceRoute: typeof LayoutSettingsAppearanceRoute
  LayoutSettingsDangerRoute: typeof LayoutSettingsDangerRoute
  LayoutSettingsDataRoute: typeof LayoutSettingsDataRoute
  LayoutSettingsDeveloperRoute: typeof LayoutSettingsDeveloperRoute
  LayoutSettingsIntegrationsRoute: typeof LayoutSettingsIntegrationsRoute
  LayoutSettingsNotificationsRoute: typeof LayoutSettingsNotificationsRoute
  LayoutSettingsPreferencesRoute: typeof LayoutSettingsPreferencesRoute
  LayoutSettingsProfileRoute: typeof LayoutSettingsProfileRoute
  LayoutSettingsSecurityRoute: typeof LayoutSettingsSecurityRoute
  LayoutSettingsTeamsRoute: typeof LayoutSettingsTeamsRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsApiKeysRoute: LayoutSettingsApiKeysRoute,
  LayoutSettingsAppearanceRoute: LayoutSettingsAppearanceRoute,
  LayoutSettingsDangerRoute: LayoutSettingsDangerRoute,
  LayoutSettingsDataRoute: LayoutSettingsDataRoute,
  LayoutSettingsDeveloperRoute: LayoutSettingsDeveloperRoute,
  LayoutSettingsIntegrationsRoute: LayoutSettingsIntegrationsRoute,
  LayoutSettingsNotificationsRoute: LayoutSettingsNotificationsRoute,
  LayoutSettingsPreferencesRoute: LayoutSettingsPreferencesRoute,
  LayoutSettingsProfileRoute: LayoutSettingsProfileRoute,
  LayoutSettingsSecurityRoute: LayoutSettingsSecurityRoute,
  LayoutSettingsTeamsRoute: LayoutSettingsTeamsRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutBrowserRoute: typeof LayoutBrowserRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutCodeRoute: typeof LayoutCodeRoute
  LayoutConnectorsRoute: typeof LayoutConnectorsRoute
  LayoutOcrRoute: typeof LayoutOcrRoute
  LayoutOsintRoute: typeof LayoutOsintRoute
  LayoutRagRoute: typeof LayoutRagRoute
  LayoutScrapingRoute: typeof LayoutScrapingRoute
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutSocialMonitoringRoute: typeof LayoutSocialMonitoringRoute
  LayoutStorageRoute: typeof LayoutStorageRoute
  LayoutTeamsRoute: typeof LayoutTeamsRoute
  LayoutWorkflowsRoute: typeof LayoutWorkflowsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutBrowserRoute: LayoutBrowserRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutCodeRoute: LayoutCodeRoute,
  LayoutConnectorsRoute: LayoutConnectorsRoute,
  LayoutOcrRoute: LayoutOcrRoute,
  LayoutOsintRoute: LayoutOsintRoute,
  LayoutRagRoute: LayoutRagRoute,
  LayoutScrapingRoute: LayoutScrapingRoute,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutSocialMonitoringRoute: LayoutSocialMonitoringRoute,
  LayoutStorageRoute: LayoutStorageRoute,
  LayoutTeamsRoute: LayoutTeamsRoute,
  LayoutWorkflowsRoute: LayoutWorkflowsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TeamsInvitationsAcceptRoute: TeamsInvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
